# Generated by Django 5.1.3 on 2024-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_is_admin_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
