# Generated by Django 5.1.3 on 2024-11-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
