# Generated by Django 5.1.3 on 2024-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_task_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
