# Generated by Django 5.1.3 on 2024-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_task_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(default="Pas de déscription", max_length=255),
        ),
    ]
