# Generated by Django 5.1.3 on 2024-11-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="send_email_notification",
            field=models.BooleanField(default=True),
        ),
    ]
