# Generated by Django 5.1.3 on 2024-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_user_send_email_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("À faire", "À faire"),
                    ("En cours", "En cours"),
                    ("Terminé", "Terminé"),
                    ("Inachevé", "Inachevé"),
                ],
                default="À faire",
                max_length=20,
            ),
        ),
    ]
