# Generated by Django 5.1.3 on 2024-11-13 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_alter_task_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="due_date",
            new_name="begin_at",
        ),
    ]
