# Generated by Django 5.1.3 on 2024-11-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_rename_due_date_task_begin_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="send_email_notification",
            field=models.BooleanField(default=False),
        ),
    ]
